name: CI/CD Workflow with Git Diff Analyzer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Git Diff Analyzer
        run: node index.js --diff
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
